config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "movies#index"
  get 'reviews/index'
  get '/search' => 'movies#search', :as => 'search_page'
  get '/movies_top/', to: 'movies#top', as: 'top'
  resources :movies do 
    post 'reviews'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :movie
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :entity, polymorphic: true
  has_one_attached :image
end

app/models/crew.rb
class Crew < ApplicationRecord
    has_and_belongs_to_many :movies ,join_table: 'crew_movies'
    
    scope :find_year, -> { where('birthday > ?', Date.parse('1990-01-01')) }
    scope :lang, -> (language,country) { where(language: language, country: country ) }

end

app/models/crew_movie.rb
class CrewMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :crew

  scope :find_role, -> { where('role=? and movie_id=?')}
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    
    has_many :reviews, :dependent => :destroy
    has_many :watchlists
    has_many :articles
    has_many :crew_movies
    has_many :assets
    has_many_attached :images
    has_one_attached :image

    has_and_belongs_to_many :crews, join_table: "crew_movies"
    
    scope :search, -> (name){ where(name: name.upcase) }
    scope :top_rate , -> { Movie.order(rating: :DESC) }

end 

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5}

  after_save do
    self.movie.update(rating: Review.where(movie: movie).sum(:rating) / Review.where(movie: movie).count)
  end

  # scope :rates, -> {joins}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show 
    @movie = Movie.find(params[:id])
    @review = Review.new 
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :new
    end
  end


  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_path
    end
  end

  def reviews
    @review = Review.create(review_params)
    if @review.save
      redirect_to movies_path
    end
  end


  def top
    @movies = Movie.top_rate
  end

  def search  
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @movies = Movie.all.where("lower(name) LIKE :search", search: @parameter)  
    end  
  end


  def review_params
    params.require(:review).permit(:user_id ,:movie_id ,:rating ,:comment  )
  end

  def movie_params
    params.require(:movie).permit(:name, :discription, :category ,:release_date ,:rating, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  # def show
  #   @reviews = Review.new
  # end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <body>
    <title>Imdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= root_path %>">Imdb</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
             <%= form_tag(search_page_path, :method => "get",   
              class: 'navbar-form navbar-left') do %>  
              <div class="input-group">  
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
              <div class="input-group-btn">  
              %= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
              </div>  
            </div>  
            <% end %>
          </div>

          <p class="navbar-text float-right">
          <% if user_signed_in? %>
            <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
      </nav>

    <div class="container">
    <div>
    <p></p><div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/movies/edit.html.slim
h3 Edit Movie 
= form_for @movie do |f|
  div
  = f.label :Name, class: "form-label"
  = f.text_field :name, class: "form-control"
  div
  = f.label :Discription
  = f.text_field :discription, class: "form-control"
  div
  = f.label :Category, class: "form-label"
  = f.text_field :category, class: "form-control"
  div
  = f.label :release_date, class: "form-label"
  = f.date_field :release_date, class: "form-control"
  div
   br
  = f.button :submit, class:"btn btn-primary"

app/views/movies/index.html.slim
div
h2 Movies List
table.table
  thead
    tr
      th scope="col"  Image
      th scope="col"  Name
      th scope="col"  Edit Movie
      th scope="col"  Delete Movie
      th scope="col"  Details
    tbody
      -@movies.each do |f|
        tr
          -if f.image.attached?
            td = image_tag f.image
          -else
            td = 0
          td = f.name
          td = link_to "Edit", edit_movie_path(f), class: "btn btn-danger"
          td = link_to "Delete", f, method: :delete, class: "btn btn-danger"
          td = link_to "Details", movie_path(f), class: "btn btn-danger"

table.table
 th = link_to "Add New Movie", new_movie_path, class: "btn btn-primary" 
 th = link_to "Top Movies", top_path, class: "btn btn-primary"

app/views/movies/new.html.slim
h3 ADD Movie
= form_for @movie do |f|
  div 
  = f.label :name, class: "form-label"
  = f.text_field :name, class: "form-control"
  div
  = f.label :discription, class: "form-label"
  = f.text_field :discription, class: "form-control"
  div
  = f.label :category, class: "form-label"
  = f.text_field :category, class: "form-control" 
  div
  = f.label :release_date, class: "form-label"
  = f.date_field :release_date, class: "form-control"
  div
  = f.label :image, class: "form-label"
  = f.file_field :image
  div
  br
  = f.button :submit, class:"btn btn-primary"

app/views/movies/search.html.slim
div
h2 Movies List
table.table
  thead
    tr
      th scope="col"  Image
      th scope="col"  Name
      th scope="col"  Edit Movie
      th scope="col"  Delete Movie
      th scope="col"  Details
    tbody
      -@movies.each do |f|
        tr
          -if f.image.attached?
            td = image_tag f.image
          -else
            td = 0
          td = f.name
          td = link_to "Edit", edit_movie_path(f), class: "btn btn-danger"
          td = link_to "Delete", f, method: :delete, class: "btn btn-danger"
          td = link_to "Details", movie_path(f), class: "btn btn-danger"




table.table
 th = link_to "add new", new_movie_path, class: "btn btn-primary" 
 th = link_to "Top Movies", top_path, class: "btn btn-primary"

app/views/movies/show.html.slim
br
h2 Movie Details
div
-if @movie.image.attached?
  td = image_tag @movie.image
-else
  td = 0
table.table
  thead
    tr
      th scope="col"  Name
      th scope="col"  Category
      th scope="col"  Discription
      th scope="col"  Release_date
      th scope="col"  Rating
  tbody
        tr
          td = @movie.name
          td = @movie.category
          td = @movie.discription
          td = @movie.release_date
          td = @movie.rating

br
div
h2 Movie Reviews
table.table
  thead
    tr
      th scope="col"  User
      th scope="col"  Comments
      th scope="col"  Rating
    tbody
      -@movie.reviews.each do |review|
        tr
          td = review.user_id
          td = review.comment
          td = review.rating
br
div
h2 Add a comment:
= form_for @review, url: movie_reviews_path(@movie) do |f|
  div 
  = f.label :user_id, class: "form-label"
  = f.text_field :user_id, class: "form-control"
  div 
  = f.label :movie_id, class: "form-label"
  = f.text_field :movie_id, class: "form-control"
  div
  = f.label :rating, class: "form-label"
  = f.text_area :rating, class: "form-control"
  div
  = f.label :comment, class: "form-label"
  = f.text_area :comment, class: "form-control"
  div
  br
  = f.button :submit, class:"btn btn-primary"
  

app/views/movies/top.html.slim
h3 Top List
table.table
  thead
    tr
      th scope="col"  Image
      th scope="col"  Name
      th scope="col"  Rating
  tbody
      - @movies.each do | f |
        tr
          -if f.image.attached?
            td = image_tag f.image, style:"border-radius: 50px;"
          -else
            td = 0
          td = f.name
          td = f.rating
    

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.slim
h3 ADD Review
= form_for model: [ @movie, @movie.rating.build ] do |f|
  p
    f.label :commenter
    f.text_field:comment
  p
    f.label :rating
    f.text_field:rating